name: Build project

on: [push, pull_request]

jobs:
  skip_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: "same_content"
          skip_after_successful_duplicate: "true"
          cancel_others: "true"
          paths_ignore: '["**/README.md"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  buildForAllSupportedPlatforms:
    needs: skip_job
    if: ${{ needs.skip_job.outputs.should_skip != 'true' }}
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: LudumDare-04-2022/Library
          key: Library-LudumDare-04-2022-WebGL
          restore-keys: |
            Library-LudumDare-04-2022-
            Library-
      - name: Build for ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: ./LudumDare-04-2022
          customImage: unityci/editor:2021.2.17f1-webgl-1.0.0
      - name: Upload ${{ matrix.targetPlatform }}
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: ${{ github.workspace }}/build/${{ matrix.targetPlatform }}
          if-no-files-found: error
